uniform_random_number – simulated-annealing
uniform_random_number Function
5 statements
Source File
private function uniform_random_number() result(f)
Get a new uniform random number from [0,1].
Author
Jacob Williams, 8/30/2019
Arguments
None
Return Value real(kind=dp)
Called by
Contents
Source Code
uniform_random_number
Source Code
    function uniform_random_number() result(f)
    implicit none
    real(dp) :: f
    call random_number(f)
    end function uniform_random_number
Call graph
sa calls uniform_random_number
uniform calls uniform_random_number
perturb_and_evaluate calls uniform